# Generated by Django 2.0.2 on 2018-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('adress', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('mobile', models.CharField(max_length=20, verbose_name='Celular')),
                ('about', models.TextField(max_length=255, verbose_name='Sobre')),
                ('birth_date', models.CharField(default=' 01 enero 2000', max_length=50, verbose_name='Fecha Nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('knowledge', models.CharField(max_length=50, verbose_name='Conocimientos')),
                ('github', models.CharField(default='https://github.com/YourGithub ', max_length=100, verbose_name='Github')),
                ('current_position', models.CharField(max_length=50, verbose_name='Empleo Actual')),
                ('companie', models.CharField(max_length=50, verbose_name='Empresa')),
            ],
        ),
    ]
